# Generated by Django 5.1.5 on 2025-02-04 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_student_new_field_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='new_field',
        ),
        migrations.RemoveField(
            model_name='student',
            name='new_field_1',
        ),
    ]
